
package minedu.reniec.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReniecWS", targetNamespace = "http://ws.reniec.minedu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReniecWS {


    /**
     * 
     * @param clave
     * @param ipsistema
     * @param persona
     * @param usuario
     * @return
     *     returns minedu.reniec.ws.MensajeError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizacionPersona", targetNamespace = "http://ws.reniec.minedu/", className = "minedu.reniec.ws.ActualizacionPersona")
    @ResponseWrapper(localName = "actualizacionPersonaResponse", targetNamespace = "http://ws.reniec.minedu/", className = "minedu.reniec.ws.ActualizacionPersonaResponse")
    public MensajeError actualizacionPersona(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "clave", targetNamespace = "")
        String clave,
        @WebParam(name = "ipsistema", targetNamespace = "")
        String ipsistema,
        @WebParam(name = "persona", targetNamespace = "")
        Persona persona);

    /**
     * 
     * @param clave
     * @param ipsistema
     * @param usuario
     * @param dni
     * @return
     *     returns minedu.reniec.ws.RespuestaReniecRemapeo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarDNICascada", targetNamespace = "http://ws.reniec.minedu/", className = "minedu.reniec.ws.BuscarDNICascada")
    @ResponseWrapper(localName = "buscarDNICascadaResponse", targetNamespace = "http://ws.reniec.minedu/", className = "minedu.reniec.ws.BuscarDNICascadaResponse")
    public RespuestaReniecRemapeo buscarDNICascada(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "clave", targetNamespace = "")
        String clave,
        @WebParam(name = "ipsistema", targetNamespace = "")
        String ipsistema,
        @WebParam(name = "dni", targetNamespace = "")
        String dni);

    /**
     * 
     * @param continente
     * @param clave
     * @param ipsistema
     * @param tipdoc
     * @param usuario
     * @param numdoc
     * @param pais
     * @return
     *     returns minedu.reniec.ws.RespuestaReniec
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarExtranjero", targetNamespace = "http://ws.reniec.minedu/", className = "minedu.reniec.ws.BuscarExtranjero")
    @ResponseWrapper(localName = "buscarExtranjeroResponse", targetNamespace = "http://ws.reniec.minedu/", className = "minedu.reniec.ws.BuscarExtranjeroResponse")
    public RespuestaReniec buscarExtranjero(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "clave", targetNamespace = "")
        String clave,
        @WebParam(name = "ipsistema", targetNamespace = "")
        String ipsistema,
        @WebParam(name = "continente", targetNamespace = "")
        String continente,
        @WebParam(name = "pais", targetNamespace = "")
        String pais,
        @WebParam(name = "tipdoc", targetNamespace = "")
        String tipdoc,
        @WebParam(name = "numdoc", targetNamespace = "")
        String numdoc);

    /**
     * 
     * @param clave
     * @param ipsistema
     * @param dniinicio
     * @param usuario
     * @param dni
     * @param dnifin
     * @return
     *     returns minedu.reniec.ws.RespuestaReniecRemapeo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarDNICascadaMasivo", targetNamespace = "http://ws.reniec.minedu/", className = "minedu.reniec.ws.BuscarDNICascadaMasivo")
    @ResponseWrapper(localName = "buscarDNICascadaMasivoResponse", targetNamespace = "http://ws.reniec.minedu/", className = "minedu.reniec.ws.BuscarDNICascadaMasivoResponse")
    public RespuestaReniecRemapeo buscarDNICascadaMasivo(
        @WebParam(name = "dniinicio", targetNamespace = "")
        String dniinicio,
        @WebParam(name = "dnifin", targetNamespace = "")
        String dnifin,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "clave", targetNamespace = "")
        String clave,
        @WebParam(name = "ipsistema", targetNamespace = "")
        String ipsistema,
        @WebParam(name = "dni", targetNamespace = "")
        String dni);

    /**
     * 
     * @param ruc
     * @param clave
     * @param ipsistema
     * @param usuario
     * @return
     *     returns minedu.reniec.ws.RespuestaEntidad
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarEntidad", targetNamespace = "http://ws.reniec.minedu/", className = "minedu.reniec.ws.BuscarEntidad")
    @ResponseWrapper(localName = "buscarEntidadResponse", targetNamespace = "http://ws.reniec.minedu/", className = "minedu.reniec.ws.BuscarEntidadResponse")
    public RespuestaEntidad buscarEntidad(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "clave", targetNamespace = "")
        String clave,
        @WebParam(name = "ipsistema", targetNamespace = "")
        String ipsistema,
        @WebParam(name = "ruc", targetNamespace = "")
        String ruc);

}
