
package minedu.reniec.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReniecWSService", targetNamespace = "http://ws.reniec.minedu/", wsdlLocation = "http://192.168.210.187:8080/prjMINEDU/ReniecWS?wsdl")
public class ReniecWSService
    extends Service
{

    private final static URL RENIECWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException RENIECWSSERVICE_EXCEPTION;
    private final static QName RENIECWSSERVICE_QNAME = new QName("http://ws.reniec.minedu/", "ReniecWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.210.187:8080/prjMINEDU/ReniecWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RENIECWSSERVICE_WSDL_LOCATION = url;
        RENIECWSSERVICE_EXCEPTION = e;
    }

    public ReniecWSService() {
        super(__getWsdlLocation(), RENIECWSSERVICE_QNAME);
    }

    public ReniecWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RENIECWSSERVICE_QNAME, features);
    }

    public ReniecWSService(URL wsdlLocation) {
        super(wsdlLocation, RENIECWSSERVICE_QNAME);
    }

    public ReniecWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RENIECWSSERVICE_QNAME, features);
    }

    public ReniecWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReniecWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReniecWS
     */
    @WebEndpoint(name = "ReniecWSPort")
    public ReniecWS getReniecWSPort() {
        return super.getPort(new QName("http://ws.reniec.minedu/", "ReniecWSPort"), ReniecWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReniecWS
     */
    @WebEndpoint(name = "ReniecWSPort")
    public ReniecWS getReniecWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.reniec.minedu/", "ReniecWSPort"), ReniecWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RENIECWSSERVICE_EXCEPTION!= null) {
            throw RENIECWSSERVICE_EXCEPTION;
        }
        return RENIECWSSERVICE_WSDL_LOCATION;
    }

}
