
package pe.gob.reniec.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReniecConsultaDni", targetNamespace = "http://ws.reniec.gob.pe/", wsdlLocation = "https://ws5.pide.gob.pe/services/ReniecConsultaDni?wsdl")
public class ReniecConsultaDni
    extends Service
{

    private final static URL RENIECCONSULTADNI_WSDL_LOCATION;
    private final static WebServiceException RENIECCONSULTADNI_EXCEPTION;
    private final static QName RENIECCONSULTADNI_QNAME = new QName("http://ws.reniec.gob.pe/", "ReniecConsultaDni");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ws5.pide.gob.pe/services/ReniecConsultaDni?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RENIECCONSULTADNI_WSDL_LOCATION = url;
        RENIECCONSULTADNI_EXCEPTION = e;
    }

    public ReniecConsultaDni() {
        super(__getWsdlLocation(), RENIECCONSULTADNI_QNAME);
    }

    public ReniecConsultaDni(WebServiceFeature... features) {
        super(__getWsdlLocation(), RENIECCONSULTADNI_QNAME, features);
    }

    public ReniecConsultaDni(URL wsdlLocation) {
        super(wsdlLocation, RENIECCONSULTADNI_QNAME);
    }

    public ReniecConsultaDni(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RENIECCONSULTADNI_QNAME, features);
    }

    public ReniecConsultaDni(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReniecConsultaDni(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReniecConsultaDniPortType
     */
    @WebEndpoint(name = "ReniecConsultaDniHttpsSoap11Endpoint")
    public ReniecConsultaDniPortType getReniecConsultaDniHttpsSoap11Endpoint() {
        return super.getPort(new QName("http://ws.reniec.gob.pe/", "ReniecConsultaDniHttpsSoap11Endpoint"), ReniecConsultaDniPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReniecConsultaDniPortType
     */
    @WebEndpoint(name = "ReniecConsultaDniHttpsSoap11Endpoint")
    public ReniecConsultaDniPortType getReniecConsultaDniHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.reniec.gob.pe/", "ReniecConsultaDniHttpsSoap11Endpoint"), ReniecConsultaDniPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RENIECCONSULTADNI_EXCEPTION!= null) {
            throw RENIECCONSULTADNI_EXCEPTION;
        }
        return RENIECCONSULTADNI_WSDL_LOCATION;
    }

}
