
package pe.gob.pj.verificacionantecedentespenalesws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PJAntecedentesPenalesPortType", targetNamespace = "http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PJAntecedentesPenalesPortType {


    /**
     * 
     * @param xProcesoEntidadConsultante
     * @param xCodigoRespuesta
     * @param xMotivoConsulta
     * @param xApellidoMaterno
     * @param xAudNombreUsuario
     * @param xAudIP
     * @param xDni
     * @param xAudNombrePC
     * @param xNombre3
     * @param xNombre2
     * @param xNombre1
     * @param xRucEntidadConsultante
     * @param xAudDireccionMAC
     * @param xMensajeRespuesta
     * @param xIpPublica
     * @param xApellidoPaterno
     * @param xDniPersonaConsultante
     */
    @WebMethod(action = "http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe/NewOperation")
    @RequestWrapper(localName = "verificarAntecedentesPenales", targetNamespace = "http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe", className = "pe.gob.pj.verificacionantecedentespenalesws.ws.VerificarAntecedentesPenales")
    @ResponseWrapper(localName = "verificarAntecedentesPenalesResponse", targetNamespace = "http://ws.verificacionAntecedentesPenalesWS.pj.gob.pe", className = "pe.gob.pj.verificacionantecedentespenalesws.ws.VerificarAntecedentesPenalesResponse")
    public void verificarAntecedentesPenales(
        @WebParam(name = "xApellidoPaterno", targetNamespace = "")
        String xApellidoPaterno,
        @WebParam(name = "xApellidoMaterno", targetNamespace = "")
        String xApellidoMaterno,
        @WebParam(name = "xNombre1", targetNamespace = "")
        String xNombre1,
        @WebParam(name = "xNombre2", targetNamespace = "")
        String xNombre2,
        @WebParam(name = "xNombre3", targetNamespace = "")
        String xNombre3,
        @WebParam(name = "xDni", targetNamespace = "")
        String xDni,
        @WebParam(name = "xMotivoConsulta", targetNamespace = "")
        String xMotivoConsulta,
        @WebParam(name = "xProcesoEntidadConsultante", targetNamespace = "")
        String xProcesoEntidadConsultante,
        @WebParam(name = "xRucEntidadConsultante", targetNamespace = "")
        String xRucEntidadConsultante,
        @WebParam(name = "xIpPublica", targetNamespace = "")
        String xIpPublica,
        @WebParam(name = "xDniPersonaConsultante", targetNamespace = "")
        String xDniPersonaConsultante,
        @WebParam(name = "xAudNombrePC", targetNamespace = "")
        String xAudNombrePC,
        @WebParam(name = "xAudIP", targetNamespace = "")
        String xAudIP,
        @WebParam(name = "xAudNombreUsuario", targetNamespace = "")
        String xAudNombreUsuario,
        @WebParam(name = "xAudDireccionMAC", targetNamespace = "")
        String xAudDireccionMAC,
        @WebParam(name = "xCodigoRespuesta", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> xCodigoRespuesta,
        @WebParam(name = "xMensajeRespuesta", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> xMensajeRespuesta);

}
